
[packmode]
	#ATM = 0 SLOP = 1 SKY = 2 MAGIC = 3 EXPERT = 4
	#Range: 0 ~ 4
	enable = 0

[discord]
	#Enable Discord Rich Prescence
	discord = true

[packversionmaj]
	#Pack Release Version Format : X
	#Range: 0 ~ 32768
	major = 1

[packversionmin]
	#Pack Minor Version : X
	#Range: 0 ~ 32768
	minor = 7

[packversionminrev]
	#Pack Minor Version Revision : X
	#Range: 0 ~ 32768
	minorrev = 11

