
[items]
	#Whether the Kitty Slippers and Bunny Hoppers should modify the player's hurt sounds
	modify_hurt_sounds = true
	#Whether models for gloves should display on the player's hand in first person
	show_first_person_glove = true
	#Whether artifacts should have a tooltip explaining their effect. These can still be found in JEI when disabled
	show_tooltips = true

[Mimics]
	#Whether mimics should use chest textures from Lootr or Quark if either of these mods is installed
	use_modded_textures = true

