
[rendering]
	#Defines how close to the position of a particle/floating texture you have to be in order for it to render.
	#Range: 1.0 ~ 512.0
	maxEffectRenderDistance = 64.0
	#Sets the amount of particles/effects
	#Allowed Values: NONE, MINIMAL, LOWERED, ALL
	particleAmount = "ALL"
	#Enables/Disables all patreon effects.
	patreonEffects = true
	#Defines the minimum y-level the fosic resonator will display the fosic field on.
	#Range: 0 ~ 256
	minYFosicDisplay = 0
	#Whitelist of dimension ID's that will have special astral sorcery sky rendering
	skyRenderingEnabled = ["minecraft:overworld"]
	#If a dimension is listed here, the skyrender will only render constellations on top of the existing skybox.
	skyRenderingConstellations = []

