#
#Elite Exporter Speed
#Range: 1 ~ 9
eliteexporterspeed = 2
#
#Elite Importer Speed
#Range: 1 ~ 9
eliteimporterspeed = 2
#
#Elite Constructor Speed
#Range: 1 ~ 20
eliteconstructorspeed = 2
#
#Elite Destructor Speed
#Range: 1 ~ 20
elitedestructorspeed = 2
#
#Elite Energy Cost Multiplier
#Range: > 0
eliteenergycost = 2
#
#Ultra Exporter Speed
#Range: 1 ~ 9
ultraexporterspeed = 6
#
#Ultra Importer Speed
#Range: 1 ~ 9
ultraimporterspeed = 6
#
#Ultra Constructor Speed
#Range: 1 ~ 20
ultraconstructorspeed = 6
#
#Ultra Destructor Speed
#Range: 1 ~ 20
ultradestructorspeed = 6
#
#Ultra Energy Cost Multiplier
#Range: > 0
ultraenergycost = 4
#
#Creative Energy Cost Multiplier
#Range: > 0
creativeenergycost = 0
#
#Elite Disk Manipulator Speed
#Range: 1 ~ 20
elitediskmanipulatorspeed = 2
#
#Ultra Disk Manipulator Speed
#Range: 1 ~ 20
ultradiskmanipulatorspeed = 6
#
#Elite Requester Max Craft Amount
#Range: > 1
eliterequestermaxcraftamount = 2000
#
#Ultra Requester Max Craft Amount
#Range: > 1
ultrarequestermaxcraftamount = 6000

