#
#Centrifuge Tier 3 output Multiplier
#Range: > 1
centrifugeTier3Mutliplier = 2
#
#Centrifuge Tier 4 output Multiplier
#Range: > 1
centrifugeTier4Mutliplier = 3
#
#Centrifuge Tier 5 output Multiplier
#Range: > 1
centrifugeTier5Mutliplier = 4
#
#Centrifuge Tier Creative output Multiplier
#Range: > 1
centrifugeTierCreativeMutliplier = 10
#
#Centrifuge Tier 3 Recipe Time 
#The Value Multiplies the Recipe Time
#Range: 0.001 ~ 100.0
centrifugeTier3RecipeTime = 0.333
#
#Centrifuge Tier 4 Recipe Time 
#The Value Multiplies the Recipe Time
#Range: 0.001 ~ 100.0
centrifugeTier4RecipeTime = 0.25
#
#Centrifuge Tier 5 Recipe Time 
#The Value Multiplies the Recipe Time
#Range: 0.001 ~ 100.0
centrifugeTier5RecipeTime = 0.125
#
#Centrifuge Tier Recipe Time 
#The Value is the Tick for the Recipe Time 
#If you set the Value to 0 the Game will Crash :)
#Range: -1 ~ 500
centrifugeTierCreativeRecipeTime = 1
#
#Centrifuge Tier 3 RF per Block Multiplier
#Range: > 1
centrifugeTier3RFPerBlockMutliplier = 2
#
#Centrifuge Tier 4 RF per Block Multiplier
#Range: > 1
centrifugeTier4RFPerBlockMutliplier = 4
#
#Centrifuge Tier 5 RF per Block Multiplier
#Range: > 1
centrifugeTier5RFPerBlockMutliplier = 8
#
#Centrifuge Tier 3 RF Capacity Multiplier
#Range: > 1
centrifugeTier3CapacityMutliplier = 20
#
#Centrifuge Tier 4 RF Capacity Multiplier
#Range: > 1
centrifugeTier4CapacityMutliplier = 40
#
#Centrifuge Tier 5 RF Capacity Multiplier
#Range: > 1
centrifugeTier5CapacityMutliplier = 80
#
#Centrifuge Tier Creative 3x3x3 Size 
#Should it be 3x3x3?
centrifugeTierCreativeSize = false
#
#Centrifuge Tier 3 Max Tank Capacity
#Range: > 1
centrifugeTier3MaxTankCapacity = 100000
#
#Centrifuge Tier 4 Max Tank Capacity
#Range: > 1
centrifugeTier4MaxTankCapacity = 200000
#
#Centrifuge Tier 5 Max Tank Capacity
#Range: > 1
centrifugeTier5MaxTankCapacity = 400000
#
#Centrifuge Tier Creative Max Tank Capacity
#Range: > 1
centrifugeTierCreativeMaxTankCapacity = 5000000
#
#Centrifuge Tier 3 Item Max Stack Size
#Range: > 1
centrifugeTier3ItemMaxStackSize = 256
#
#Centrifuge Tier 4 Item Max Stack Size
#Range: > 1
centrifugeTier4ItemMaxStackSize = 512
#
#Centrifuge Tier 5 Item Max Stack Size
#Range: > 1
centrifugeTier5ItemMaxStackSize = 1024
#
#Centrifuge Tier Creative Item Max Stack Size
#Range: > 1
centrifugeTierCreativeItemMaxStackSize = 16384

