
#General configuration options.
[General]
	#Mod ids (in order) to prioritize using items for when generating the cucumber-tags.json file.
	modTagPriorities = ["thermal", "mekanism", "tconstruct", "immersiveengineering", "appliedenergistics2"]

