
[general]
	#Wether ghost blocks are shown when you are holding a framed block
	showGhostBlocks = true
	#Wether certain framed blocks should show fancy hitboxes
	fancyHitboxes = true
	#If false only full block faces of framed blocks will be culled, if true all outer faces of famed blocks can be culled
	detailedCulling = true

