
#Biome config
#To filter biomes by registry name "mod_id:biome_id"
#To filter biomes by category "@category"
#To filter biomes by tags "#tag"
#	Examples:
#		"minecraft:plains"
#		"@desert"
#		"#overworld"
#
#If you want to exclude biomes put a ! before the biome identifier
#	Examples:
#		"!minecraft:plains"
#		"!@desert"
#		"!#nether"
#
#If you want to include biomes that would be satisfied by any in a set use |
#	Examples:
#		"|minecraft:plains"
#		"|@desert"
#		"|#nether"
#
#If you want a condition that MUST be satisfied use an & before the biome identifier
#Please note using this on a registry name wouldn't be that useful
#	Examples:
#		"&minecraft:plains"
#		"&@forest"
#		"&#overworld"
#
#NOTE: Any entry without a !, |, or & symbol has a higher precedence
#A list like ["!minecraft:plains", "#overworld"] would still see the plains as a viable biome
#
#Finally, you can create a expression that can be evaluated by itself using a + to combine identifiers
#	Examples:
#		"!#hot+!#dry+!#mountain"
#
#These expressions can be used to filter biomes in a lot of ways
#Lets say we don't want anything to spawn in any place dry and sandy
#	"!#dry+!#sandy"
#
#But there is a hot place we want them to spawn that's also wet
#	"#hot+#wet"
#
#We just put them as separate values in the list and that'll work out
#	["!#dry+!#sandy","#hot+#wet"]
#
#NOTE: Any entry that's an expression will not be affected by anything else in the list
[biome_configs]
	deathwormBiomes = ["allthemodium:desert"]
	lightningDragonBiomes = ["allthemodium:soul_sand_valley"]
	cockatriceBiomes = ["allthemodium:nether_wastes"]
	blackHippogryphBiomes = ["minecraft:desert_hills"]
	lightningLilyBiomes = ["&#overworld+|@savanna+|#savanna"]
	sirenBiomes = [""]
	amphithereBiomes = ["allthemodium:nether_wastes"]
	fireDragonSkeletonBiomes = ["allthemodium:desert"]
	brownHippogryphBiomes = ["&#overworld+|#mountains+|@extreme_hills"]
	amethystBiomes = ["&#overworld+|@savanna+|#savanna"]
	hippocampusBiomes = [""]
	snowyTrollBiomes = ["allthemodium:soul_sand_valley"]
	hippogryphBiomes = ["&#overworld+|#mesa+|#mountains+|#hills+|@extreme_hills"]
	iceDragonSkeletonBiomes = ["allthemodium:eroded_badlands"]
	jungleMyrmexBiomes = ["allthemodium:crimson_forest", "allthemodium:warped_forest"]
	mausoleumBiomes = ["allthemodium:the_other"]
	sapphireBiomes = ["&#overworld+&#snowy+|@icy+|#cold+"]
	mountainTrollBiomes = ["allthemodium:mountain_edge"]
	iceLilyBiomes = ["&#overworld+&#snowy+|@icy+|#cold+"]
	chestnutHippogryphBiomes = ["minecraft:wooded_mountains"]
	pixieBiomes = ["allthemodium:warped_forest"]
	creamyHippogryphBiomes = ["minecraft:savanna_plateau"]
	overworldSpawnBiomes = ["allthemodium:the_other"]
	forestTrollBiomes = ["allthemodium:crimson_forest", "allthemodium:warped_forest"]
	grayHippogryphBiomes = ["minecraft:dark_forest_hills"]
	seaSerpentBiomes = [""]
	cyclopsCaveBiomes = ["allthemodium:gravelly_mountains"]
	stymphalianBiomes = ["allthemodium:mountains"]
	gorgonTempleBiomes = ["allthemodium:desert"]
	hydraBiomes = ["allthemodium:mountain_edge"]
	whiteHippogryphBiomes = ["minecraft:snowy_mountains", "minecraft:snowy_taiga_mountains", "minecraft:snowy_taiga_hills"]
	fireLilyBiomes = ["&#overworld+|#hot+"]
	graveyardBiomes = ["allthemodium:soul_sand_valley"]
	oreGenBiomes = ["|#overworld"]
	iceDragonBiomes = ["allthemodium:mountain_edge"]
	darkBrownHippogryphBiomes = ["minecraft:taiga_mountains", "minecraft:taiga_hills"]
	wanderingCyclopsBiomes = ["allthemodium:nether_wastes"]
	desertMyrmexBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	lightningDragonSkeletonBiomes = ["allthemodium:badlands_plateau", "allthemodium:the_other"]
	fireDragonBiomes = ["allthemodium:basalt_deltas", "allthemodium:the_other"]

