
[general]
	#How fast amphitheres fly.
	#Range: 0.0 ~ 3.0
	"Amphithere Flight Speed" = 2.75
	#how long(in ticks) a siren has to wait after failing to lure in a player
	#Range: 100 ~ 24000
	"Siren Time Between Songs" = 2000
	#Troll attack strength
	#Range: 1.0 ~ 10000.0
	"Troll Attack Strength" = 40.0
	#Maximum cyclops health
	#Range: 1.0 ~ 10000.0
	"Cyclops Max Health" = 5500.0
	#Dread Lich spawn weight. Lower = lower chance to spawn
	#Range: 1 ~ 10000
	"Lich Spawn Weight" = 8000
	#Whether or not sea serpents can break weak blocks in their way
	"Sea Serpent Griefing" = false
	#True if pixie villages are allowed to spawn
	"Spawn Pixies" = true
	#How many blocks away can cyclopes detect sheep. Note that increasing this could cause lag.
	#Range: 1 ~ 10000
	"Cyclopes Sheep Search Length" = 17
	#A double check to see if the game can spawn death worms. Higher number = lower chance to spawn.
	#Range: 0 ~ 10000
	"Death Worm Spawn Check Chance" = 300
	#Maximum cockatrice health
	#Range: 1.0 ~ 10000.0
	"Cockatrice Health" = 1000.0
	#True if gorgon temples are allowed to spawn
	"Spawn Gorgons" = true
	#True if hippocampi are allowed to spawn
	"Spawn Hippocampus" = false
	#Damage dealt from a successful ice breath attack. Attack Damage is scaled to by age, so a stage 5 dragon will deal 5x as much as this number
	#Range: 0.0 ~ 10000.0
	"Dragon Attack Damage(Ice breath)" = 150.0
	#How high dragons can fly, in Y height.
	#Range: > 100
	"Max Dragon Flight Height" = 250
	#True if cockatrices are allowed to spawn
	"Spawn Cockatrices" = true
	#True if tamed dragons go to sleep at night.
	"Tamed Dragons Sleep" = true
	#True if ghosts can rarely spawn from brutal PvP deaths.
	"Ghost Spawn from PvP deaths" = false
	#Whether or not cyclops can break logs or leaves in their way
	"Cyclops Griefing" = true
	#Disable this to remove easter egg with tinkers installed.
	Weezer = false
	#True if dragons can despawn. Note that if this is false there may be SERIOUS lag issues.
	"Dragons Despawn" = true
	#True if hippogryphs are allowed to spawn
	"Spawn Hippogryphs" = true
	#True if dread liches are allowed to spawn
	"Spawn Liches" = true
	#One out of this number chance per chunk to generate a mausoleum.
	#Range: 1 ~ 10000
	"Mausoleum Gen Chance" = 30
	#Whether to generate copper ore or not
	"Generate Copper Ore" = false
	#A more intelligent dragon pathfinding system, but is also laggier. Turn this on if you think dragons are too stupid.
	"Intelligent Dragon Pathfinding" = false
	#Cockatrice spawn weight. Lower = lower chance to spawn
	#Range: 1 ~ 10000
	"Cockatrice Spawn Weight" = 10
	#True to make the screen pink when sirens attract players
	"Use Siren Shader" = false
	#Enable this if your server is being bombarded with moved wrongly or moved too fast console messages. REQUIRES RESTART!
	"Dragon Moved Wrongly Error Fix" = true
	#Blocks that a dragon can break, but won't spawn drops for. Use the format like "minecraft:stone" or "rats:block_of_cheese" 
	noDropBreakBlocks = ["minecraft:netherrack", "minecraft:dirt", "minecraft:grass_block", "minecraft:stone", "minecraft:soul_sand"]
	#How many blocks away can death worms spot potential prey. Note that increasing this could cause lag
	#Range: 1 ~ 10000
	"Death Worm Target Search Length" = 64
	#How far away stymphalian birds will consider other birds to be in the same flock.
	#Range: 1 ~ 10000
	"Stymphalian Bird Flock Length" = 40
	#How many maximum individuals a myrmex colony can have.
	#Range: 10 ~ 10000
	"Myrmex Colony Max Size" = 20
	#1 out of this number chance per block that gold will generate in dragon lairs.
	#Range: 1 ~ 10000
	"Dragon Den Gold Amount" = 3
	#Whether to generate dragon skeletons or not
	"Generate Dragon Skeletons" = true
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Cyclops Cave Chance" = 100
	#True if myrmex colonies are allowed to spawn
	"Spawn Myrmex" = true
	#Default attack strength of a dragonsteel sword.
	#Range: 5.0 ~ 2.147483647E9
	"Dragonsteel Sword Base Attack Strength" = 1350.0
	#Whether to generate dragon caves or not
	"Generate Dragon Caves" = true
	#How high stymphalian birds can fly, in Y height.
	#Range: > 10
	"Max Stymphalian Bird Flight Height" = 200
	#Whitelist mob spawn (troll, hippogryph, etc) dimensions. Use the format like "minecraft:the_nether" or "rats:ratlantis" 
	blacklistDimensions = ["allthemodium:the_other"]
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Sea Serpent Chance" = 250
	#Default sea serpent health, this is scaled to the sea serpent's particular size
	#Range: 1.0 ~ 10000.0
	"Sea Serpent Base Health" = 20.0
	#True if chickens lay rotten eggs.
	"Chickens Lay Rotten Eggs" = false
	#size of pixie villages
	#Range: 1 ~ 10000
	"Pixie Village Size" = 5
	#Maximum amphithere health
	#Range: 1.0 ~ 10000.0
	"Amphithere Max Health" = 2500.0
	#How many ticks it takes while riding an untamed amphithere to tame it.
	#Range: 1 ~ 10000
	"Amphithere Tame Time" = 400
	#True if dragons can break blocks if they get stuck. Turn this off if your dragons randomly explode.
	"Dragons Dig When Stuck" = true
	#True if siren islands are allowed to spawn
	"Spawn Sirens" = false
	#True if tamed dragons can follow the griefing rules.
	"Tamed Dragon Griefing" = true
	#Default deathworm attack strength, this is scaled to the worm's particular size
	#Range: 1.0 ~ 10000.0
	"Death Worm Base Attack Strength" = 23.0
	#Maximum hydra health
	#Range: 1.0 ~ 10000.0
	"Hydra Max Health" = 10000.0
	#Maximum gorgon health
	#Range: 1.0 ~ 10000.0
	"Gorgon Max Health" = 8000.0
	#Whether to generate silver ore or not
	"Generate Silver Ore" = false
	#Turning this to true simplifies the dragon's pathfinding process, making them dumber when finding a path, but better for servers with many loaded dragons.
	"Experimental Dragon path Finder" = true
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Generate Dragon Skeleton Chance" = 3000
	#True if villagers should run away and hide from dragons and other hostile Ice and Fire mobs.
	"Villagers Fear Dragons" = true
	#1 out of this number chance per 6000 ticks for a chicken to lay a cockatrice egg.
	#Range: > 1
	"Cockatrice chicken Search Length" = 30
	#True if cyclops caves are allowed to spawn
	"Spawn Cyclopes Caves" = true
	#True if hydra caves are allowed to generate
	"Generate Hydra Caves" = true
	#Default armor value of dragonsteel chestplate.
	#Range: > 7
	"Dragonsteel Base Armor" = 1420
	#How many blocks away can dragons wander from their defined "home" position.
	#Range: 1 ~ 10000
	"Dragon Wander From Home Distance" = 40
	#True if using blacklists, false if using whitelists for dragons and structure gen.
	"Use Dimension Blacklist" = false
	#Default deathworm health, this is scaled to the worm's particular size
	#Range: 1.0 ~ 10000.0
	"Death Worm Base Health" = 3000.0
	#Change this to slow down or speed up dragon or amphithere flight.
	#Range: 0.0 ~ 2.0
	"Dragon Flight Speed Modifier" = 1.0
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Wandering Cyclops Chance" = 100
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Gorgon Chance" = 8
	#Default durability value of dragonsteel sword.
	#Range: > 1
	"Dragonsteel Base Durability" = 18000
	#How many blocks away can stymphalian birds spot potential prey. Note that increasing this could cause lag.
	#Range: 1 ~ 10000
	"Stymphalian Bird Target Search Length" = 64
	#True if stymphalian birds are allowed to target and attack animals
	"Stymphalian Birds Target Animals" = false
	#How many ticks it takes for a Myrmex to move from a larva to a pupa, and from a pupa to an adult.
	#Range: 1 ~ 100000
	"Myrmex Hatch Length" = 35000
	#Whether to generate graveyards or not
	"Generate Graveyards" = true
	#True if trolls are allowed to spawn
	"Spawn Trolls" = true
	#True if amphitheres are allowed to spawn
	"Spawn Amphitheres" = true
	#Whether to generate sapphire ore or not
	"Generate Sapphire Ore" = true
	#Maximum ghost health.
	#Range: 1.0 ~ 10000.0
	"Ghost Max Health" = 3000.0
	#How far away dangerous structures(dragon roosts, cyclops caves, etc.) must be from spawn(0, 0).
	#Range: 1 ~ 10000
	"Dangerous World Gen Dist From Spawn" = 1500
	#Damage dealt from a successful lightning breath attack. Attack Damage is scaled to by age, so a stage 5 dragon will deal 5x as much as this number
	#Range: 0.0 ~ 10000.0
	"Dragon Attack Damage(Lightning breath)" = 125.0
	#One out of this number chance per chunk to generate a myrmex hive.
	#Range: 1 ~ 10000
	"Myrmex Colony Gen Chance" = 150
	#Hippogryph spawn weight. Lower = lower chance to spawn.
	#Range: 1 ~ 10000
	"Hippogryph Spawn Weight" = 2
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Generate Dragon Roost Chance" = 3
	#Maximum ghost attack strength.
	#Range: 0.0 ~ 10000.0
	"Ghost Attack Strength" = 20.0
	#One out of this number chance per chunk to generate a hydra cave.
	#Range: 1 ~ 10000
	"Hydra Caves Gen Chance" = 10
	#Every interval of this number in ticks, dragon allowed to break blocks.
	#Range: 0 ~ 10000
	"Dragon Block Break Cooldown" = 10
	#True if stymphalian birds are allowed to spawn
	"Spawn Stymphalian Birds" = true
	#True if dragons can drop their blood on death.
	"Dragons Drop Blood" = true
	#Every interval of this number in ticks, dragon hunger decreases.
	#Range: 1 ~ 10000
	"Dragon Hunger Tick Rate" = 3000
	#True if trolls are allowed to drop their weapon on death.
	"Trolls Drop Weapon" = true
	#Troll spawn weight. Lower = lower chance to spawn
	#Range: 1 ~ 10000
	"Troll Spawn Weight" = 4000
	#Glacier Spawn Weight. Higher number = more common
	#Range: 1 ~ 10000
	"Glacier Spawn Weight" = 400
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Generate Dragon Cave Chance" = 4
	#Dragon griefing - 2 is no griefing, 1 is breaking weak blocks, 0 is default
	#Range: 0 ~ 2
	"Dragon Griefing" = 0
	#A double check to see if the game can spawn cockatrices. Higher number = lower chance to spawn.
	#Range: 0 ~ 10000
	"Cockatrice Spawn Check Chance" = 2000
	#True if pixies are allowed to steal from players
	"Pixies Steal Items" = false
	#True if dragons can drop their heart on death.
	"Dragons Drop Heart" = true
	#True if wild deathworms are allowed to target and attack monsters
	"Death Worms Target Monsters" = false
	#How far away dangerous structures(dragon roosts, cyclops caves, etc.) must be from the last generated structure.
	#Range: 1 ~ 10000
	"Dangerous World Gen Dist Seperation" = 500
	#True if dragons fire/ice charges create secondary explosions that launch blocks everywhere. Turn this to true if you like unfair explosions. Or lag.
	"Explosive Dragon Breath" = false
	#Maximum threads to use for dragon/myrmex pathfinding. Increase this number if pathing is slow and you have many cores.
	#Range: > 1
	"Dragon Pathfinding Threads" = 3
	#Base Myrmex(worker) attack strength
	#Range: 1.0 ~ 10000.0
	"Myrmex Base Attack Strength" = 28.0
	#How far away dragons will detect gold blocks being destroyed or chests being opened
	#Range: 0 ~ 10000
	"Dragon Gold Search Length" = 30
	#True if stymphalian birds can drop items registered in the ore dictionary to ingotCopper, ingotBronze, nuggetCopper, nuggetBronze.
	"Stymphalian Birds drop ore dict items" = false
	#True if animals should run away and hide from dragons and other hostile Ice and Fire mobs.
	"Animals Fear Dragons" = true
	#Stymphalian bird feather attack strength.
	#Range: 0.0 ~ 10000.0
	"Stymphalian Bird Feather Attack Strength" = 5.0
	#Blocks that a dragon cannot break. Use the format like "minecraft:chest" or "rats:block_of_cheese" 
	blacklistedBreakBlocks = []
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Hippocampus Chance" = 40
	#Amphithere spawn weight. Lower = lower chance to spawn
	#Range: 1 ~ 10000
	"Amphithere Spawn Weight" = 1500
	#Dragon Flute Distance - how many chunks away is the dragon flute effective?
	#Range: 0 ~ 10000
	"Dragon Flute Distance" = 4
	#The percentage chance for a block to drop as an item when a dragon breaks it.
	#Range: 0.0 ~ 1.0
	"Dragon Block Breaking Drop Chance" = 0.10000000149011612
	#Damage dealt from a successful fire breath attack. Attack Damage is scaled to by age, so a stage 5 dragon will deal 5x as much as this number
	#Range: 0.0 ~ 10000.0
	"Dragon Attack Damage(Fire breath)" = 90.0
	#How many blocks away can ampitheres detect villagers being hurt. Note that increasing this could cause lag.
	#Range: 1 ~ 10000
	"Amphithere Villager Search Length" = 64
	#Deathworm spawn weight. Higher = lower chance to spawn
	#Range: 1 ~ 10000
	"Death Worm Spawn Weight" = 30
	#Percentage of critical strike that will disarm with easter egg tinkers material.
	#Range: 0.0 ~ 1.0
	"Easter Egg Tinkers Tool Disarm chance" = 0.20000000298023224
	#Whether to generate amethyst ore or not
	"Generate Amethyst Ore" = true
	#Ratio of Stone(this number) to Ores in Dragon Caves
	#Range: 1 ~ 10000
	"Dragon Cave Ore Ratio" = 45
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Stymhphalian Bird Chance" = 80
	#A double check to see if the game can spawn trolls. Higher number = lower chance to spawn.
	#Range: 0 ~ 10000
	"Troll Spawn Check Chance" = 0
	#1/this number chance for a stymphalian feather to turn into an item before despawning. Zero means never.
	#Range: 0 ~ 10000
	"Stymphalian Bird Feather Drop Chance" = 25
	#How long it takes(in ticks) for a dragon egg to hatch
	#Range: > 1
	"Dragon Egg Hatch Time" = 7200
	#Cyclops attack strength
	#Range: 1.0 ~ 10000.0
	"Cyclops Attack Strength" = 55.0
	#how long(in ticks) can a siren use its sing effect on a player, without a cooldown.
	#Range: 100 ~ 24000
	"Siren Max Sing Time" = 12000
	#Max dragon health. Health is scaled to this
	#Range: 1.0 ~ 100000.0
	"Dragon Health" = 65535.0
	#How many blocks away can dragons spot potential prey. Note that increasing this could cause lag.
	#Range: 1 ~ 10000
	"Dragon Target Search Length" = 128
	#How many ticks it takes for a Myrmex Queen to produce an egg.
	#Range: 1 ~ 10000
	"Myrmex Gestation Length" = 2500
	#Whether to generate glacier biomes or not
	"Generate Glaciers" = true
	#True if wandering cyclopes are allowed to spawn
	"Spawn Wandering Cyclopes" = true
	#Maximum siren health
	#Range: 1.0 ~ 10000.0
	"Siren Max Health" = 50.0
	#True if dragons can drop their skull on death.
	"Dragons Drop Skull" = true
	#True if sea serpents are allowed to spawn
	"Spawn Sea Serpents" = false
	#Maximum nodes for dragons/myrmex to path too. Decrease this is dragon pathfinding is super slow or intensive.
	#Range: > 1
	"Dragon Max Pathfinding Nodes" = 5000
	#True if the summon crystal can load chunks to find dragons.
	"Chunk Load Summon Crystal" = true
	#Amount of damage done with cyclops bite attack.
	#Range: 1.0 ~ 10000.0
	"Cyclops Bite Strength" = 70.0
	#Amphithere attack strength
	#Range: 1.0 ~ 10000.0
	"Amphithere Attack Strength" = 27.0
	#Graveyard rarity.
	#Range: 2 ~ 10000
	"Graveyard Chance" = 20
	#Max dragon attack damage. Attack Damage is scaled to this
	#Range: 1 ~ 10000
	"Dragon Attack Damage" = 70
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Sirens Chance" = 1400
	#Maximum troll health
	#Range: 1.0 ~ 10000.0
	"Troll Max Health" = 5000.0
	#Default sea serpent attack strength, this is scaled to the sea serpent's particular size
	#Range: 1.0 ~ 10000.0
	"Sea Serpent Base Attack Strength" = 4.0
	#Whether to generate dragon roosts or not
	"Generate Dragon Roosts" = true
	#True if mausoleums are allowed to generate
	"Generate Mausoleums" = true
	#Dragon Flap Noise Distance - Larger number, further away you can hear it
	#Range: 0 ~ 10000
	"Dragon Flap Noise Distance" = 4
	#True if deathworms are allowed to spawn
	"Spawn Death Worms" = true
	#1 out of this number chance per chunk for generation
	#Range: 1 ~ 10000
	"Spawn Pixies Chance" = 40

