
#General configuration options.
[General]
	#Should jetpacks be enachantable?
	enchantableJetpacks = true

#Dynamic recipe options.
[Recipe]
	#Enable default recipes for Energy Cells?
	cells = true
	#Enable default recipes for Thrusters?
	thrusters = true
	#Enable default recipes for Capacitors?
	capacitors = true
	#Enable default recipes for Jetpacks?
	jetpacks = true

