
[afk]
	auto = true
	#Range: > 0
	auto_kick = 0
	#Range: > 1
	auto_time = 600

#Command Config
[Commands]

	[Commands.broadcast]
		#Enable command: /broadcast
		enable = false

	[Commands.repair]
		#Enable command: /repair
		enable = false

	[Commands.endc]
		#Enable command: /endc
		enable = false

	[Commands.back]
		#Range: > 0
		death_custom_cooldown = 0
		#Range: > 0
		delay = 3
		#Enable command: /back
		enable = false
		#Range: > 0
		cooldown = 0
		enable_on_death = false

	[Commands.speed]
		#Range: 0 ~ 50
		max_walk_speed = 20
		#Enable command: /speed
		enable = false
		#Range: 0 ~ 50
		max_fly_speed = 20

	[Commands.head]
		#Enable command: /head
		enable = false

	[Commands.warps]
		#Range: > 0
		delay = 3
		#Enable commands: /setwarp, /delwarp, /warp
		enable = false
		#Range: > 0
		cooldown = 0

	[Commands.top]
		#Enable command: /top
		enable = false

	[Commands.kickall]
		#Enable command: /kickall
		enable = false

	[Commands.weather]
		#Enable commands: /sun, /rain, /thunder
		enable = false

	[Commands.heal]
		#Enable command: /heal
		enable = false

	[Commands.homes]
		#Range: > 0
		delay = 3
		#Enable commands: /sethome, /delhome, /home
		enable = false
		#Range: > 0
		cooldown = 0
		#Range: > 1
		limit = 3
		#Range: > 1
		limit_op = 5

	[Commands.hat]
		#Enable command: /hat
		enable = false

	[Commands.up]
		#Enable command: /up
		enable = false

	[Commands.tempban]
		#Enable command: /check
		enable = false

	[Commands.rndtp]
		#Range: > 0
		delay = 3
		#Enable command: /rndtp
		enable = true
		#Range: > 0
		cooldown = 0
		#Range: 50 ~ 999
		range_min = 500
		#Range: > 1000
		range_max = 2000

	[Commands.tpa]
		#Range: > 0
		delay = 3
		#Enable commands: /tpa, /tpahere, /tpaccept, /tpdeny
		enable = false
		#Range: > 0
		cooldown = 0
		#Range: > 0
		timeout = 20

	[Commands.gm]
		#Enable command: /gm
		enable = false

	[Commands.suicide]
		enable_player = false
		#Enable command: /suicide
		enable = false
		#Range: > 0
		cooldown_player = 20

	[Commands.afk]
		#Range: > 0
		cooldown = 30
		command = false

	[Commands.mute]
		#Enable commands: /mute, /unmute
		enable = false

	[Commands.kits]
		#Enable command: /kit
		enable = false
		starting_kit = false
		starting_kit_name = "tools"

	[Commands.trash]
		#Enable command: /trash
		enable = false

	[Commands.invsee]
		#Enable command: /invsee
		enable = false

	[Commands.fly]
		#Enable command: /fly
		enable = false

	[Commands.tpall]
		#Enable command: /tpall
		enable = false

	[Commands.spawn]
		#Range: > 0
		delay = 3
		#Enable commands: /spawn, /setspawn
		enable = false
		#Range: > 0
		cooldown = 0
		force_spawn_on_death = false

	[Commands.time]
		#Enable commands: /day, /night
		enable = false

	[Commands.god]
		#Enable command: /god
		enable = false

