
#All configuration items related to the core gameplay
[gameplay]
	#minecolonies.config.enablecitizenvoices.comment [Default: true]
	enablecitizenvoices = true
	#By default, when placing a schematic near other buildings, the already-placed buildings will show as if they were at level 5 and have a blue outline around them. You can disable that by setting this to false. [Default: true]
	neighborbuildingrendering = true

#All configurations related to pathfinding
[pathfinding]
	#Show pathfinding paths (might be laggy). [Default: false]
	pathfindingdebugdraw = false

