
#Disable and configure tweaks.
[Tweaks]
	#Tools and weapons that should be ineffective.
	#Ex: ["minecraft:stone_pickaxe", "minecraft:stone_sword"]
	uselessTools = []
	#Enabled tools not breaking?
	toolBreaking = false

#Crafting grid tool repair configuration options.
["Grid Repair"]
	#Makes it so shovels need 50% less material to repair.
	cheapShovel = true
	#How much material should be required to fully repair a tool.
	#Range: 1 ~ 8
	cost = 4
	#Should default repair materials be disabled? Doing this makes it so ONLY the custom materials work.
	disableDefaults = false
	#Tools that should not be repairable in the crafting grid.
	#Ex: ["minecraft:stone_pickaxe", "minecraft:stone_sword"]
	blacklist = []
	#Here you can specify custom repair materials for tools.
	#Ex: ["minecraft:stone_shovel=minecraft:stick"]
	#You can use tags for materials by doing tag:<tag-id>.
	#Ex: ["minecraft:stone_shovel=tag:forge:ingots/iron"]
	#You can specify how effective the material is by appending @<multiplier>
	#Ex: ["minecraft:stone_shovel=minecraft:stick@0.5"]
	overrides = []
	#Should Crafting Grid Tool Repairing be enabled?
	enabled = false
	#Enabling this makes it so custom repair materials override the default ones for the tools specified.
	overrideMode = false

#General configuration options.
[General]
	#The effective radius of the Magnet.
	#Range: 1.0 ~ 16.0
	magnetRange = 7.0

#Disable features.
[Features]
	#Dark Glass enabled?
	darkGlass = false
	#Enable Emerald tools and armor?
	emeraldGear = false
	#Colored Cobblestone enabled?
	coloredCobblestone = false
	#Watering Can enabled?
	wateringCan = false
	#Enable Paxels?
	paxels = false
	#Enable Night Vision Goggles?
	nightVisionGoggles = false
	#Enable Magnet?
	magnet = false
	#Coal and Charcoal Piece enabled?
	coalPiece = true
	#Enable Flint tools and armor?
	flintGear = false
	#Enable right click crop harvesting?
	rightClickHarvest = false
	#Smooth Glowstone enabled?
	smoothGlowstone = false
	#Diamond and Emerald Apples enabled?
	apples = true
	#Enable Meshes?
	meshes = false

