
#Common Settings
[common]
	#Turns on/off loot added to various vanilla chest loot tables
	chestLootEnabled = true
	#Disable / enable any items here (disables their recipes)
	enabledItems = ["backpack:true", "iron_backpack:true", "gold_backpack:true", "diamond_backpack:true", "netherite_backpack:true", "pickup_upgrade:true", "advanced_pickup_upgrade:true", "filter_upgrade:true", "advanced_filter_upgrade:true", "magnet_upgrade:true", "advanced_magnet_upgrade:true", "feeding_upgrade:true", "compacting_upgrade:true", "advanced_compacting_upgrade:true", "void_upgrade:true", "advanced_void_upgrade:true", "restock_upgrade:true", "advanced_restock_upgrade:true", "deposit_upgrade:true", "advanced_deposit_upgrade:true", "refill_upgrade:true", "inception_upgrade:true", "everlasting_upgrade:true", "smelting_upgrade:true", "auto_smelting_upgrade:true", "crafting_upgrade:true", "stonecutter_upgrade:true", "stack_upgrade_tier_1:true", "stack_upgrade_tier_2:true", "stack_upgrade_tier_3:true", "stack_upgrade_tier_4:true", "jukebox_upgrade:true", "tool_swapper_upgrade:true", "advanced_tool_swapper_upgrade:true", "upgrade_base:true", "tank_upgrade:true"]

	#Advanced Filter Upgrade Settings
	[common.advancedFilterUpgrade]
		#Number of Advanced Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Void Upgrade Settings
	[common.advancedVoidUpgrade]
		#Number of Advanced Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Advanced Magnet Upgrade Settings
	[common.advancedMagnetUpgrade]
		#Number of Advanced Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 5
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Pickup Upgrade Settings
	[common.pickupUpgrade]
		#Number of Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Diamond Backpack Settings
	[common.diamondBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 5
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 108

	#Filter Upgrade Settings
	[common.filterUpgrade]
		#Number of Filter Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Compacting Upgrade Settings
	[common.compactingUpgrade]
		#Number of Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Compacting Upgrade Settings
	[common.advancedCompactingUpgrade]
		#Number of Advanced Compacting Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Void Upgrade Settings
	[common.voidUpgrade]
		#Number of Void Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Tool Swapper Upgrade Settings
	[common.toolSwapperUpgrade]
		#Number of tool filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Inception Upgrade Settings
	[common.inceptionUpgrade]
		#Allows / Disallows backpack upgrades to work with inventories of Backpacks in the Backpack with Inception Upgrade
		upgradesUseInventoriesOfBackpacksInBackpack = true
		#Allows / Disallows upgrades to be functional even when they are in Backpacks in the inventory of Backpack with Inception Upgrade
		upgradesInContainedBackpacksAreFunctional = true

	#Restock Upgrade Settings
	[common.restockUpgrade]
		#Number of Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Advanced Deposit Upgrade Settings
	[common.advancedDepositUpgrade]
		#Number of Advanced Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Netherite Backpack Settings
	[common.netheriteBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 7
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 120

	#Deposit Upgrade Settings
	[common.depositUpgrade]
		#Number of Deposit Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Auto-Smelting Upgrade Settings
	[common.autoSmeltingUpgrade]
		#Number of fuel filter slots displayed in a row
		#Range: 1 ~ 6
		fuelFilterSlotsInRow = 4
		#Number of input filter slots
		#Range: 1 ~ 20
		inputFilterSlots = 8
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Number of fuel filter slots
		#Range: 1 ~ 20
		fuelFilterSlots = 4
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0
		#Number of input filter slots displayed in a row
		#Range: 1 ~ 6
		inputFilterSlotsInRow = 4

	#Advanced Restock Upgrade Settings
	[common.advancedRestockUpgrade]
		#Number of Advanced Restock Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Leather Backpack Settings
	[common.leatherBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 1
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 27

	#Gold Backpack Settings
	[common.goldBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 3
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 81

	#Iron Backpack Settings
	[common.ironBackpack]
		#Number of upgrade slots in the backpack
		#Range: 0 ~ 10
		upgradeSlotCount = 2
		#Number of inventory slots in the backpack
		#Range: 1 ~ 144
		inventorySlotCount = 54

	#Feeding Upgrade Settings
	[common.feedingUpgrade]
		#Number of Feeding Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Magnet Upgrade Settings
	[common.magnetUpgrade]
		#Number of Magnet Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 9
		#Range around backpack in blocks at which magnet will pickup items
		#Range: 1 ~ 20
		magnetRange = 3
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Smelting Upgrade Settings
	[common.smeltingUpgrade]
		#Smelting speed multiplier (1.0 equals speed at which vanilla furnace smelts items)
		#Range: 0.25 ~ 4.0
		smeltingSpeedMultiplier = 1.0
		#Fuel efficiency multiplier (1.0 equals speed at which it's used in vanilla furnace)
		#Range: 0.25 ~ 4.0
		fuelEfficiencyMultiplier = 1.0

	#Advanced Pickup Upgrade Settings
	[common.advancedPickupUpgrade]
		#Number of Advanced Pickup Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 16
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 4

	#Refill Upgrade Settings
	[common.refillUpgrade]
		#Number of Refill Upgrade's filter slots
		#Range: 1 ~ 20
		filterSlots = 6
		#Number of filter slots displayed in a row
		#Range: 1 ~ 6
		slotsInRow = 3

	#Settings for Spawning Entities with Backpack
	[common.entityBackpackAdditions]
		#Chance of an entity spawning with Backpack
		#Range: 0.0 ~ 1.0
		chance = 0.01
		#Turns on/off buffing the entity that wears backpack with potion effects. These are scaled based on how much loot is added.
		buffWithPotionEffects = true
		#Map of entities that can spawn with backpack and related loot tables (if adding a loot is enabled) in format of "EntityRegistryName|LootTableName"
		entityLootTableList = ["minecraft:creeper|minecraft:chests/desert_pyramid", "minecraft:drowned|minecraft:chests/shipwreck_treasure", "minecraft:enderman|minecraft:chests/end_city_treasure", "minecraft:evoker|minecraft:chests/woodland_mansion", "minecraft:husk|minecraft:chests/desert_pyramid", "minecraft:piglin|minecraft:chests/bastion_bridge", "minecraft:piglin_brute|minecraft:chests/bastion_treasure", "minecraft:pillager|minecraft:chests/pillager_outpost", "minecraft:skeleton|minecraft:chests/simple_dungeon", "minecraft:stray|minecraft:chests/igloo_chest", "minecraft:vex|minecraft:chests/woodland_mansion", "minecraft:vindicator|minecraft:chests/woodland_mansion", "minecraft:witch|minecraft:chests/buried_treasure", "minecraft:wither_skeleton|minecraft:chests/nether_bridge", "minecraft:zombie|minecraft:chests/simple_dungeon", "minecraft:zombie_villager|minecraft:chests/village/village_armorer", "minecraft:zombified_piglin|minecraft:chests/bastion_other"]
		#List of music discs that are not supposed to be played by entities
		discBlockList = ["botania:record_gaia_1", "botania:record_gaia_2"]
		#Turns on/off buffing the entity that wears backpack with additional health. Health is scaled based on backpack tier the mob wears.
		buffHealth = true
		#Turns on/off equiping the entity that wears backpack with armor. What armor material and how enchanted is scaled based on backpack tier the mob wears.
		equipWithArmor = true
		#Turns on/off addition of loot into backpacks
		addLoot = true
		#Turns on/off a chance that the entity that wears backpack gets jukebox upgrade and plays a music disc.
		playJukebox = false

	#Tank Upgrade Settings
	[common.tankUpgrade]
		#Capacity in mB the tank upgrade will have per row of backpack slots
		#Range: 500 ~ 20000
		capacityPerSlotRow = 2000
		#Ratio that gets applied (multiplies) to inventory stack multiplier before this is applied to tank capacity. Value lower than 1 makes stack multiplier affect the capacity less, higher makes it affect the capacity more. 0 turns off stack multiplier affecting tank capacity
		#Range: 0.0 ~ 5.0
		stackMultiplierRatio = 1.0
		#Cooldown between fill/drain actions done on fluid containers in tank slots. Only fills/drains one bucket worth to/from container after this cooldown and then waits again.
		#Range: 1 ~ 100
		autoFillDrainContainerCooldown = 20

