
#Everything to do with gameplay
[gameplay]
	#If true, requires slimeballs in the vanilla slimeblock recipe to match in color, otherwise gives a pink slimeblock
	requireSlimeballsToMatchInVanillaRecipe = true
	#Add a recipe that allows you to craft a piece of flint using 3 gravel
	addGravelToFlintRecipe = true
	#If true all material variants of the different parts will be listed in creative. Set to false to only have the first found material for all parts (usually wood).
	listAllPartMaterials = true
	#Set this to false to disable new players spawning with the Tinkers' Book.
	shouldSpawnWithTinkersBook = true
	#If true all material variants of the different tools will be listed in creative. Set to false to only have the first found material for all tools (usually wood).
	listAllToolMaterials = true
	#Blacklist of registry names for the crafting station to connect to. Mainly for compatibility.
	craftingStationBlacklist = []
	#Pattern and Part chests keep their inventory when harvested.
	chestsKeepInventory = true
	#If true, all recipes will be added even if the modules required are disabled.
	registerAllRecipes = false

#Everything to do with world generation
[worldgen]
	#Generate Ardite
	generateArdite = true
	#Generate Cobalt
	generateCobalt = true
	#Approx Ores per Chunk
	veinCountArdite = 20
	#Set this to false to disable slime islands spawning in the world
	generateSlimeIslands = true
	#Generate Copper
	generateCopper = false
	#Approx Ores per Chunk
	veinCountCobalt = 20
	#Approx Ores per Chunk
	veinCountCopper = 20

