
#Allows to customize or disable the enchantments
[enchantments]
	#Enables the enchantment Soulbound [false/true|default:true]
	enable_enchantment_soulbound = false
	#Shadow Step is only active while sneaking [false/true|default:false]
	nerf_shadow_step = false
	#Enables the enchantment Shadow Step [false/true|default:true]
	enable_enchantment_shadow_step = true
	#Enables the enchantment Magic Siphon [false/true|default:true]
	enable_enchantment_magic_siphon = true
	#Enables the enchantment Plague Bringer [false/true|default:true]
	enable_enchantment_plague_bringer = true
	#Enables the enchantment Curse of Bones [false/true|default:true]
	enable_enchantment_curse_of_bones = true
	#Enables the enchantment Blessing [false/true|default:true]
	enable_enchantment_blessing = true
	#Allows Soulbound at enchanting table [false/true|default:false]
	soulbound_enchanting_table = true
	#Allows Shadow Step at enchanting table [false/true|default:false]
	shadow_step_enchanting_table = false
	#Allows Magic Siphon at enchanting table [false/true|default:false]
	magic_siphon_enchanting_table = false
	#Allows Plague Bringer at enchanting table [false/true|default:false]
	plague_bringer_enchanting_table = false
	#Allows Curse of Bones at enchanting table [false/true|default:false]
	curse_of_bones_enchanting_table = false
	#Allows Blessing at enchanting table [false/true|default:false]
	blessing_enchanting_table = false
	#Allows Plague Bringer to combine with Magic Siphon [false/true|default:false]
	plague_bringer_combining_magic_siphon = false
	#Max level for Shadow Step [1..10|default:5]
	#Range: 1 ~ 10
	max_level_shadow_step = 5
	#Max level for Magic Siphon [1..10|default:5]
	#Range: 1 ~ 10
	max_level_magic_siphon = 5
	#Max level for Plague Bringer [1..10|default:5]
	#Range: 1 ~ 10
	max_level_plague_bringer = 5
	#Max level for Curse of Bones [1..10|default:5]
	#Range: 1 ~ 10
	max_level_curse_of_bones = 5

#Options related to player's death
[player_death]
	#Experience loss on death (%) (-1 = disabled) [-1..100|default:80]
	#Range: -1 ~ 100
	xp_loss = 0
	#The time in minutes before a Grave's Key isn't required to open a grave (-1 = disabled) [-1..MAX|default:-1]
	#Range: > -1
	decay_time = -1
	#Allows players with bad alignment and the perk tomb raider to steal items on abandoned graves [false/true|default:false]
	allow_tomb_raiding = false

#Miscellaneous options
[general]
	#The duration of the Ghostly Shape effect in seconds [0..MAX|default:120]
	#Range: > 0
	ghostly_shape_duration = 120
	#The chance that a player receives an already enchanted Grave's Key on death [-1..100|default:0|disabled:-1]
	#Range: -1 ~ 100
	chance_enchanted_grave_key = 0
	#Required level in Knowledge of Death to craft Familiar Receptacle [0..20|default:10]
	#Range: 0 ~ 20
	familiar_receptacle_required_level = 10
	#Scroll duration [1200..120000|default:12000]
	#Range: 1200 ~ 120000
	scroll_duration = 12000

#For settings related to decorative tombs and magic items
[decorative_grave]
	#Maximum uses of a tablet [1..10|default:3]
	#Range: 1 ~ 10
	tablet_max_use = 10
	#Cooldown in second after using a tablet [60..1200|default:300]
	#Range: 60 ~ 1200
	tablet_cooldown = 60
	#Sets the decorative graves unbreakable [false/true|default:false]
	unbreakable_decorative_grave = false
	#The cooldown in hours to pray with the Ankh [1..10|default:3]
	#Range: 1 ~ 10
	cooldown_to_pray = 3
	#The cooldown in minutes to reset the perks with the ankh of Pray [20..1440|default:120]
	#Range: 20 ~ 1440
	cooldown_reset_perk = 20

#Allows to disable some magic items
[allowedMagicItems]
	#Voodoo Poppet [false/true|default:true]
	allow_voodoo_poppet = true
	#Familiar Receptacle [false/true|default:true]
	allow_familiar_receptacle = true
	#Book of Disenchantment [false/true|default:true]
	allow_book_of_disenchantment = true
	#Scroll of Preservation [false/true|default:true]
	allow_scroll_of_preservation = true
	#Grave's Key [false/true|default:true]
	allow_grave_key = true
	#Scroll of Knowledge [false/true|default:true]
	allow_scroll_of_knowledge = true
	#Tablet of Recall [false/true|default:true]
	allow_tablet_of_recall = true
	#Tablet of Home [false/true|default:true]
	allow_tablet_of_home = true
	#Tablet of Assistance [false/true|default:true]
	allow_tablet_of_assistance = true
	#Tablet of Cupidity [false/true|default:true]
	allow_tablet_of_cupidity = true
	#Scroll of Unstable Intangibleness [false/true|default:true]
	allow_scroll_of_unstable_intangibleness = true
	#Scroll of Feather Fall [false/true|default:true]
	allow_scroll_of_feather_fall = true
	#Scroll of Purification [false/true|default:true]
	allow_scroll_of_purification = true
	#Scroll of True Sight [false/true|default:true]
	allow_scroll_of_true_sight = true
	#Lost Tablet [false/true|default:true]
	allow_lost_tablet = true
	#Scroll of Reach [false/true|default:true]
	allow_scroll_of_reach = true
	#Scroll of Lightning Resistance [false/true|default:true]
	allow_scroll_of_lightning_resistance = true
	#Dust of Vanishing [false/true|default:true]
	allow_dust_of_vanishing = true
	#Scroll of Frost Resistance [false/true|default:true]
	allow_scroll_of_frost_resistance = true
	#Scroll of Aquatic Life [false/true|default:true]
	allow_scroll_of_aquatic_life = true

#Allows to change the chance to drop some items
[loot]
	#Chance to loot a Lost Tablet by fishing [0..1000|default:100]
	#Range: 0 ~ 1000
	chance_loot_lost_tablet = 100

