#Allows to customize or disable the enchantments
[enchantments]
	enable_enchantment_soulbound = false

[player_death]
	xp_loss = 0
[decorative_grave]
	tablet_max_use = 10
	tablet_cooldown = 60
	cooldown_reset_perk = 20
