
#Personal Options that can be edited even on server
[client]
	#Fog density around the graves [NONE/LOW/NORMAL/HIGH|default:LOW]
	#Allowed Values: NONE, LOW, NORMAL, HIGH
	fog_density = "LOW"
	#Decimal value for the color of the particles when using magic items [0..16777215|default:125656]
	#Range: 0 ~ 16777215
	particle_casting_color = 14937088
	#Shows the magic circles when using some items [false/true|default:true]
	show_magic_circle = true
	#Shows all the infos in the tooltip of items [false/true|default:true]
	show_enhanced_tooltips = true
	#Highlights the tomb from far when holding the key [false/true|default:true]
	highlight = true
	#Skips the Respawn Screen [false/true|default:false]
	skip_respawn_screen = false
	#Shows shadow step particles [false/true|default:true]
	show_shadow_step = true
	#Shows shield particles on villager [false/true|default:true]
	show_shield_particle = true
	#Enables the special rendering and particles for Halloween [false/true|default:true]
	enable_halloween_effect = true
	#Decimal value for the color of the grave text <Death Date> [0..16777215|default:2962496]
	#Range: 0 ~ 16777215
	text_color_death_date = 2962496
	#Decimal value for the color of the grave text <R.I.P.> [0..16777215|default:2962496]
	#Range: 0 ~ 16777215
	text_color_rip = 2962496
	#Decimal value for the color of the grave text <Owner Name> [0..16777215|default:5991302]
	#Range: 0 ~ 16777215
	text_color_owner = 5991302
	#Shows only the elapsed minecraft days since the death on graves [false/true|default:false]
	date_in_mc_time = false
	#Display or not the messages of gain of points in knowledge of death [false/true|default:true]
	display_knowledge_message = true
	#Equips elytra in priority when recovering your lost items [false/true|default:false]
	equip_elytra_in_priority = false
	#Favorite grave
	#Allowed Values: GRAVE_SIMPLE, GRAVE_NORMAL, GRAVE_CROSS, TOMBSTONE, SUBARAKI_GRAVE, GRAVE_ORIGINAL
	favorite_grave = "GRAVE_SIMPLE"
	#Favorite grave marble
	#Allowed Values: DARK, WHITE
	favorite_grave_marble = "DARK"
	#Shows the use of the Tombstone's enchantments in tooltip [false/true|default:true]
	show_info_on_enchantment = true
	#Defines the rule to use for grave's skin [DEFAULT/FORCE_NORMAL/FORCE_HALLOWEEN|default:DEFAULT]
	#Allowed Values: DEFAULT, FORCE_NORMAL, FORCE_HALLOWEEN
	grave_skin_rule = "DEFAULT"
	#Favor the tools on the hotbar when recovering a grave [false/true|default:false]
	priorize_tool_on_hotbar = false
	#Decimal value of the fog color [0..16777215|default:125656]
	#Range: 0 ~ 16777215
	fog_color = 16777215
	#Period where graves produce fog [DAY/NIGHT/BOTH|default:NIGHT]
	#Allowed Values: DAY, NIGHT, BOTH, NEVER
	fog_period = "NIGHT"
	#Allows to activate a grave by sneaking [false/true|default:true]
	activate_grave_by_sneaking = true
	#Denies to create a grave with your items when you die [false/true|default:false]
	deny_grave_on_death = false
	#Allows your grave to appear in water [false/true|default:true]
	allow_grave_in_water = true
	#Defines your grave placement logic (nearest or ideal placement) [SAFEST/NORMAL/NEAREST|default:NORMAL]
	#Allowed Values: SAFEST, NORMAL, NEAREST
	grave_spawn_rule = "NORMAL"
	#Defines when to automatically equip your items [NEVER/GRAVE_RECOVERY/DEATH_RESPAWN/ALWAYS|default:ALWAYS]
	#Allowed Values: NEVER, GRAVE_RECOVERY, DEATH_RESPAWN, ALWAYS
	auto_equip_rule = "ALWAYS"

