
[misc]
	#The amount of days till the insomnia overlay is rendered
	#Setting to 3 will make the overlay indicate phantom spawns
	#Setting to 0 will disable the overlay
	"Days until insomnia overlay" = 0

