
#Settings for the factory
[factory]

	[factory.general]
		#Allow tick acceleration to be used on the factory
		tickAcceleration = true
		#Max health for a tier 2 mob
		#Range: > 5
		t2MaxHealth = 40
		#Max health for a tier 4 mob
		#Range: > 5
		t4MaxHealth = 2147483647
		#Max health for a tier 5 mob
		#Range: > 5
		t5MaxHealth = 2147483647
		#Max health for a tier 3 mob
		#Range: > 5
		t3MaxHealth = 60
		#Max health for a tier 1 mob
		#Range: > 5
		t1MaxHealth = 20
		#Exotic drop chance
		#Range: 0.0 ~ 100.0
		exotic = 15.0

	[factory.basicCell]
		#Tank max transfer rate (mb/t per side)
		#Range: > 1
		tankRxPerTick = 1000
		#Tank capacity (mb)
		#Range: > 1
		tankCapacity = 10000

	[factory.ultimateCell]
		#Tank max transfer rate (mb/t per side)
		#Range: > 1
		tankRxPerTick = 25000
		#Tank capacity (mb)
		#Range: > 1
		tankCapacity = 1000000

	[factory.advancedCell]
		#Tank max transfer rate (mb/t per side)
		#Range: > 1
		tankRxPerTick = 5000
		#Tank capacity (mb)
		#Range: > 1
		tankCapacity = 50000

	[factory.perks]

		[factory.perks.tierShard]
			#Chance to drop essence from a Tier 3 factory
			#Range: 0.0 ~ 100.0
			t3DropChance = 20.0
			#Chance to drop essence from a Tier 4 factory
			#Range: 0.0 ~ 100.0
			t4DropChance = 30.0
			#Number of chances to generate essence for tier 1 perk
			#Range: > 0
			l1Rolls = 1
			#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 2 factory
			t2DropWeights = [70, 25, 1]
			#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 4 factory
			t4DropWeights = [50, 40, 1]
			#Chance to drop essence from a Tier 5 factory
			#Range: 0.0 ~ 100.0
			t5DropChance = 40.0
			#Number of chances to generate essence for tier 3 perk
			#Range: > 0
			l3Rolls = 3
			#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 5 factory
			t5DropWeights = [40, 50, 1]
			#Chance to drop essence from a Tier 1 factory
			#Range: 0.0 ~ 100.0
			t1DropChance = 5.0
			#Number of chances to generate essence for tier 2 perk
			#Range: > 0
			l2Rolls = 2
			#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 3 factory
			t3DropWeights = [60, 30, 1]
			#Chance to drop essence from a Tier 2 factory
			#Range: 0.0 ~ 100.0
			t2DropChance = 10.0
			#Weights of the Celadon, Cerulean, Byzantium shard from a Tier 1 factory
			t1DropWeights = [80, 20, 1]

		[factory.perks.efficiency]
			#Percentage reduction for efficiency 3 perks
			#Range: 0 ~ 100
			l3Reduction = 30
			#Percentage reduction for efficiency 1 perks
			#Range: 0 ~ 100
			l1Reduction = 15
			#Percentage reduction for efficiency 2 perks
			#Range: 0 ~ 100
			l2Reduction = 25

		[factory.perks.rate]
			#Percentage reduction in spawn time for rate 3 perks
			#Range: 1 ~ 99
			l3Reduction = 75
			#Percentage reduction in spawn time for rate 1 perks
			#Range: 1 ~ 99
			l1Reduction = 20
			#Percentage reduction in spawn time for rate 2 perks
			#Range: 1 ~ 99
			l2Reduction = 50

		[factory.perks.mass]
			#Number of mobs to spawn for mass 2 perks
			#Range: 1 ~ 100
			l2MobCount = 4
			#Number of mobs to spawn for mass 1 perks
			#Range: 1 ~ 100
			l1MobCount = 2
			#Number of mobs to spawn for mass 3 perks
			#Range: 1 ~ 100
			l3MobCount = 6

		[factory.perks.xp]
			#Percentage generate of XP for xp 2 perks
			#Range: 0 ~ 1000
			l2Generate = 125
			#Percentage generate of XP for xp 3 perks
			#Range: 0 ~ 1000
			l3Generate = 150
			#Percentage generate of XP for xp 1 perks
			#Range: 0 ~ 1000
			l1Generate = 100

		[factory.perks.headless]
			#Percentage chance to drop a skull for headless 1 perks
			#Range: 0 ~ 1000
			l1HeadlessChance = 25
			#Percentage chance to drop a skull for headless 2 perks
			#Range: 0 ~ 1000
			l2HeadlessChance = 50
			#Percentage chance to drop a skull for headless 3 perks
			#Range: 0 ~ 1000
			l3HeadlessChance = 80

		[factory.perks.slaughter]
			#Percentage of liquid meat and pink slime to drop for slaughter 1 perks
			#Range: 0 ~ 1000
			l1SlaughterAmount = 100
			#Percentage of liquid meat and pink slime to drop for slaughter 2 perks
			#Range: 0 ~ 1000
			l2SlaughterAmount = 120
			#Percentage of liquid meat and pink slime to drop for slaughter 3 perks
			#Range: 0 ~ 1000
			l3SlaughterAmount = 140

		[factory.perks.crusher]
			#Percentage of essence to drop for crusher 1 perks
			#Range: 0 ~ 1000
			l1CrusherAmount = 100
			#Percentage of essence to drop for crusher 2 perks
			#Range: 0 ~ 1000
			l2CrusherAmount = 120
			#Percentage of essence to drop for crusher 3 perks
			#Range: 0 ~ 1000
			l3CrusherAmount = 140

		[factory.perks.laser]
			#Percentage of ether gas to drop for laser 1 perks
			#Range: 0 ~ 1000
			l1LaserAmount = 100
			#Percentage of ether gas to drop for laser 2 perks
			#Range: 0 ~ 1000
			l2LaserAmount = 120
			#Percentage of ether gas to drop for laser 3 perks
			#Range: 0 ~ 1000
			l3LaserAmount = 140

		[factory.perks.flayed]
			#Percentage of mob health for flayed 1 perks
			#Range: 0 ~ 1000
			l1FlayedAmount = 90
			#Percentage of mob health for flayed 2 perks
			#Range: 0 ~ 1000
			l2FlayedAmount = 100
			#Percentage of mob health for flayed 3 perks
			#Range: 0 ~ 1000
			l3FlayedAmount = 110

	[factory.premiumCell]
		#Tank max transfer rate (mb/t per side)
		#Range: > 1
		tankRxPerTick = 10000
		#Tank capacity (mb)
		#Range: > 1
		tankCapacity = 100000

	[factory.base]
		#Number of ticks to spawn a mob
		#Range: 1 ~ 65535
		spawnTicks = 320
		#Number of units for each health
		#Range: 1 ~ 65535
		mbPerHealth = 10
		#Number of mobs to spawn
		#Range: 1 ~ 100
		massCount = 1
		#Number of kills to program the shard
		#Range: 1 ~ 65535
		shardKills = 5

	[factory.exotic]
		#Percentage reduction for recipe fluids
		#Range: 0.0 ~ 100.0
		exoticAPercentage = 85.0
		#Percentage reduction for recipe fluids
		#Range: 0.0 ~ 100.0
		exoticBPercentage = 85.0
		#Percentage reduction for Conatus fluid
		#Range: 0.0 ~ 100.0
		exoticCPercentage = 85.0
		#Number of ticks between spawns
		#Range: > 1
		exoticDTicks = 20
		#Number of mobs to spawn
		#Range: > 1
		exoticECount = 10

#Settings for the loot simulation
[simulation]
	#Number of mobs to simulate per simulator tick
	#Range: 1 ~ 128
	cellsPerSimTick = 32
	#Number of ticks between mob simulations
	#Range: 20 ~ 1200
	tickRate = 40
	#Number of simulated mobs to learn from
	#Range: 100 ~ 5000
	mobSampleSize = 1000
	#Number of ticks per tick of the simulator
	#Range: 1 ~ 1200
	simTickRate = 10

#Settings for the infuser
[infuser]
	#Energy used per tick (RF)
	#Range: > 0
	energyUsePerTick = 20
	#Tank capacity (mb)
	#Range: > 0
	tankCapacity = 5000
	#Maximum energy that can be received (RF/t)
	#Range: > 0
	energyRxPerTick = 100
	#Energy capacity (mb)
	#Range: > 0
	energyCapacity = 10000

#Settings for the convertor
[fluid_convertor]
	#Input tank capacity (mb)
	#Range: > 1000
	inputTankCapacity = 10000
	#Energy used per tick (RF)
	#Range: > 0
	energyUsePerTick = 20
	#Tank capacity (mb)
	#Range: > 1000
	tankCapacity = 10000
	#Maximum energy that can be received (RF/t)
	#Range: > 0
	energyRxPerTick = 100
	#Energy capacity (mb)
	#Range: > 0
	energyCapacity = 10000

#Settings for the squeezer
[squeezer]

	[squeezer.dye]
		#Energy used per tick (RF)
		#Range: > 0
		energyUsePerTick = 20
		#Tank capacity (mb)
		#Range: > 0
		tankCapacity = 4000
		#Maximum energy that can be received (RF/t)
		#Range: > 0
		energyRxPerTick = 100
		#Internal tank capacity (mb)
		#Range: > 0
		internalTankCapacity = 7200
		#Energy capacity (mb)
		#Range: > 0
		energyCapacity = 10000

	[squeezer.enchant]
		#Energy used per tick (RF)
		#Range: > 0
		energyUsePerTick = 20
		#How much energy to process a level 1 enchanted item (in RF)
		#Range: > 0
		enchantEnergyLevel1 = 1000
		#Amount of extra energy for each level above 5 (in RF)
		#Range: > 0
		enchantEnergyPerLevel = 1000
		#Amount of extra fluid for each level above 5 (in mb)
		#Range: > 0
		enchantAmountPerLevel = 500
		#How much energy to process a level 2 enchanted item (in RF)
		#Range: > 0
		enchantEnergyLevel2 = 2000
		#Amount of fluid for a level 5 enchantment (in mb)
		#Range: > 0
		enchantAmountLevel5 = 2500
		#Energy capacity (mb)
		#Range: > 0
		energyCapacity = 10000
		#Amount of fluid for a level 3 enchantment (in mb)
		#Range: > 0
		enchantAmountLevel3 = 1500
		#Amount of fluid for a level 4 enchantment (in mb)
		#Range: > 0
		enchantAmountLevel4 = 2000
		#Amount of fluid for a level I enchantment (in mb)
		#Range: > 0
		enchantAmountLevel1 = 500
		#Amount of fluid for a level 2 enchantment (in mb)
		#Range: > 0
		enchantAmountLevel2 = 1000
		#How much energy to process a level 3 enchanted item (in RF)
		#Range: > 0
		enchantEnergyLevel3 = 3000
		#How much energy to process a level 4 enchanted item (in RF)
		#Range: > 0
		enchantEnergyLevel4 = 4000
		#How much energy to process a level 5 enchanted item (in RF)
		#Range: > 0
		enchantEnergyLevel5 = 5000
		#Tank capacity (mb)
		#Range: > 0
		tankCapacity = 5000
		#Maximum energy that can be received (RF/t)
		#Range: > 0
		energyRxPerTick = 100

#Settings for the factory
[policy]

	[policy.mob]
		#Override default spawn ticks for a mob
		spawnTicks = ["minecraft:wither,1200", "minecraft:ender_dragon,12000", "botania:doppleganger,12000"]
		#Override default tier for a mob
		tier = ["minecraft:wither_skeleton,4", "minecraft:villager,4", "minecraft:magma_cube,3", "minecraft:enderman,4", "minecraft:villager_golem,4", "minecraft:guardian,4", "minecraft:blaze,3", "minecraft:witch,3", "minecraft:ghast,3", "minecraft:zombie_pigman,3", "minecraft:ender_dragon,5", "minecraft:wither,5", "botania:doppleganger,5"]
		#Override default units per health for a mob
		unitsPerHealth = []
		#Set a fixed cost for a mob
		fixedCost = []
		#Override default mass count for a mob
		massCount = []
		#Override default xp for a mob
		xp = ["minecraft:iron_golem,20", "minecraft:bat,1", "minecraft:snow_golem,1", "minecraft:villager,2", "minecraft:wandering_villager,2", "minecraft:ender_dragon,500", "botania:doppleganger,1"]
		#Override default health for a mob
		health = ["minecraft:ender_dragon,500", "botania:doppleganger,250"]
		#Override default shard kills for a mob
		shardKills = []
		#A list of mobs that should not be simulated and use custom config only
		customDropsOnly = ["minecraft:ender_dragon", "botania:doppleganger"]

		[policy.mob.perk]
			#Set mass perk level 1 for a mob
			mass1 = ["minecraft:ender_dragon,2", "minecraft:wither,2", "botania:doppleganger,2"]
			#Set mass perk level 2 for a mob
			mass2 = ["minecraft:ender_dragon,3", "minecraft:wither,3", "botania:doppleganger,3"]
			#Set mass perk level 3 for a mob
			mass3 = ["minecraft:ender_dragon,4", "minecraft:wither,4", "botania:doppleganger,4"]
			#Set rate perk level 1 for a mob
			rate1 = []
			#Set rate perk level 2 for a mob
			rate2 = []
			#Set rate perk level 3 for a mob
			rate3 = []
			#Set xp perk level 1 for a mob
			xp1 = []
			#Set xp perk level 3 for a mob
			xp3 = []
			#Set xp perk level 2 for a mob
			xp2 = []
			#Set efficiency perk level 2 for a mob
			efficiency2 = []
			#Set efficiency perk level 1 for a mob
			efficiency1 = []
			#Set efficiency perk level 3 for a mob
			efficiency3 = []
			#Set headless perk level 1 for a mob
			headless1 = []
			#Set headless perk level 2 for a mob
			headless2 = []
			#Set headless perk level 3 for a mob
			headless3 = []
			#A list of mobs and their skull drop
			headlessSkulls = ["minecraft:skeleton,{\"item\": \"minecraft:skeleton_skull\"}", "minecraft:wither_skeleton,{\"item\": \"minecraft:wither_skeleton_skull\"}", "minecraft:zombie,{\"item\": \"minecraft:zombie_head\"}", "minecraft:creeper,{\"item\": \"minecraft:creeper_head\"}"]

	[policy.blacklist]
		#Do not generate the following items
		generateItem = []
		#Do not generate items from the following mods
		generateMod = []
		#Do not allow shard creation with the following entities
		shardEntity = []
		#Do not learn items from the following mods
		learnMod = []
		#Do not capture any entity from the following mods
		captureMod = []
		#Do not capture the following entities
		captureEntity = []
		#Do not learn the following items
		learnItem = []
		#Do not allow shard creation with entities from the following mods
		shardMod = []

#Settings for commands
[commands]
	#Manual learning of a mob command level
	#Range: 0 ~ 10
	simLearnLevel = 2
	#Display loot table of a mob command level
	#Range: 0 ~ 10
	simDumpLevel = 0
	#Flush loot table of a mob command level
	#Range: 0 ~ 10
	simFlushLevel = 2
	#Show status of mob simulation command level
	#Range: 0 ~ 10
	simStatusLevel = 0
	#Test drop of a mob command level
	#Range: 0 ~ 10
	simRollDropsLevel = 0
	#Give mob controller command level
	#Range: 0 ~ 10
	giveControllerLevel = 2

