
[Overworld]

	[Overworld.Ores]

		[Overworld.Ores.Pendorite]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			PendoritePerChunk = 10
			#
			#Generate Pendorite Ore? Only spawns in Forest Fault.
			GeneratePendorite = true
			#
			#Y level to start generating at.
			#Default: 56
			#Range: 1 ~ 256
			PendoriteY = 56
			#
			#Size of the clusters.
			#Default: 4
			#Range: 1 ~ 100
			PendoriteSize = 4

		#Datapacks can and will override all values in the "Ore" category so keep that in mind!
		[Overworld.Ores.Ametrine]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			AmetrinePerChunk = 10
			#
			#Size of the clusters.
			#Default: 4
			#Range: 1 ~ 100
			AmetrineSize = 4
			#
			#Generate Ametrine Ore? Only spawns in Guiana Shield, Stone Forest, and Pointed Stone Forest!
			GenerateAmetrine = true
			#
			#Y level to start generating at.
			#Default: 56
			#Range: 1 ~ 256
			AmetrineY = 56

	[Overworld.Stones]

		[Overworld.Stones.Scoria_Stone]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			ScoriaStonePerChunk = 10
			#
			#Y level to start generating at.
			#Default: 63
			#Range: 1 ~ 256
			ScoriaStoneY = 63
			#
			#Size of the clusters.
			#Default: 20
			#Range: 1 ~ 100
			ScoriaStoneSize = 20
			#
			#Generate Scoria Stone?
			GenerateScoriaStone = true

		[Overworld.Stones.Soap_Stone]
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			SoapStonePerChunk = 10
			#
			#Size of the clusters.
			#Default: 20
			#Range: 1 ~ 100
			SoapStoneSize = 20
			#
			#Generate Soap Stone?
			GenerateSoapStone = true
			#
			#Y level to start generating at.
			#Default: 63
			#Range: 1 ~ 256
			SoapStoneY = 63

		#Datapacks can and will override all values in the "Stone" category so keep that in mind!
		[Overworld.Stones.Rocky_Stone]
			#
			#Y level to start generating at.
			#Default: 63
			#Range: 1 ~ 256
			RockyStoneY = 63
			#
			#Size of the clusters.
			#Default: 20
			#Range: 1 ~ 100
			RockyStoneSize = 20
			#
			#Number of times to spawn per chunk.
			#Default: 10
			#Range: 1 ~ 100
			RockyStonePerChunk = 10
			#
			#Generate Rocky Stone?
			GenerateRockyStone = true

[The_End]
	#
	#Does BYG control The End?
	ControlEnd = true
	#
	#Is the list of biomes a blacklist or whitelist?
	#When this list is a blacklist, the values in the list will not be in world generation.
	#When this list is a whitelist, Adding a biome several times gives it more weight in generation and it must contain at least 1 value.
	#When set to true, datapack biomes will work automatically! When set to false, you will need to manually add datapack entries.
	#Default: true
	isBlacklistEnd = true
	#
	#End Biome Size.
	#Default: 3
	#Range: 0 ~ 10
	IslandBiomeSize = 3
	#
	#This works as a whitelist or blacklist depending on the "isBlacklistEnd" value.
	#NO SPACES AFTER COMMAS!
	#Default: "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands,minecraft:the_end,minecraft:end_barrens"
	BlacklistEnd = "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands,minecraft:the_end,minecraft:end_barrens"
	#
	#End Biome Size
	#Default: 3
	#Range: 0 ~ 10
	EndBiomeSize = 3

	[The_End.Void]
		#
		#Add biomes by their registry String ID's in a commented list.
		#Adding a biome several times gives it more weight in generation.
		#NO SPACES AFTER COMMAS!
		#Default: "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands"
		VoidBiomes = "byg:viscal_isles,byg:shattered_viscal_isles,minecraft:small_end_islands"
		#
		#Void Biome(where small end islands generate in vanilla) size.
		#Default: 3
		#Range: 0 ~ 10
		VoidBiomeSize = 2

[The_Nether]
	#
	#Is the list of biomes a blacklist or whitelist?
	#When this list is a blacklist, the values in the list will not be in world generation.
	#When this list is a whitelist, Adding a biome several times gives it more weight in generation and it must contain at least 1 value.
	#When set to true, datapack biomes will work automatically! When set to false, you will need to manually add datapack entries.
	#Default: true
	isBlacklistNether = true
	#
	#Nether Biome Size
	#Default: 3
	#Range: 0 ~ 10
	NetherBiomeSize = 3
	#
	#Does BYG control The Nether?
	ControlNether = true
	#
	#This works as a whitelist or blacklist depending on the "isBlacklistNether" value.
	#NO SPACES AFTER COMMAS!
	#Default: ""
	BlacklistNether = "byg:embur_bog,allthemodium:modified_gravelly_mountains,allthemodium:gravelly_mountains,allthemodium:mining,allthemodium:badlands,allthemodium:badlands_plateau,allthemodium:basalt_deltas,allthemodium:crimson_forest,allthemodium:desert,allthemodium:desert_hills,allthemodium:eroded_badlands,allthemodium:mining,allthemodium:modified_badlands_plateau,allthemodium:mountain_edge,allthemodium:mountains,allthemodium:nether_wastes,allthemodium:soul_sand_valley,allthemodium:the_other,allthemodium:warped_forest"

#End related settings
[end]
	#Does BYG control The End?
	#This only applies when making NEW worlds!
	#Is not guaranteed to work in specific world types.
	#You can find more info here in regards to specific world types: https://github.com/CorgiTaco/BYG/wiki/Enabling-BYG-Nether-&-End-Biomes
	#For existing worlds, follow the steps listed here: https://wiki.griefed.de/SCP/edit-world.
	controlEnd = true
	#End Biome Size
	#Default: 3
	#Range: 1-10
	endBiomeSize = 3
	#Void Biome Size
	#Default: 2
	#Range: 1-10
	voidBiomeSize = 2

#Nether related settings
[nether]
	#Does BYG control The Nether?
	#This only applies when making NEW worlds!
	#Is not guaranteed to work in specific world types.
	#You can find more info here in regards to specific world types: https://github.com/CorgiTaco/BYG/wiki/Enabling-BYG-Nether-&-End-Biomes
	#For existing worlds, follow the steps listed here: https://wiki.griefed.de/SCP/edit-world.
	controlNether = true
	#Nether Biome Size
	#Default: 3
	#Range: 1-10
	netherBiomeSize = 3

#BYG uses a prefix system for its ore spawns.
# Prefix Guide:
# "#" - Biome category representable.
# "$" - Biome dictionary representable.
# "," - Creates a new condition, separate from the previous.
# "ALL" - Spawn in all biomes(no condition).
# "!" - Negates/flips/does the reverse of the condition.
# "" - No prefix serves as a biome ID OR Mod ID representable.
#
# Here are a few examples:
#1. "byg#THE_END, $OCEAN" would mean that the ore may spawn in biomes with the name space "byg" AND in the "END" biome category, OR all biomes in the "OCEAN" dictionary.
#2. "byg:guiana_shield, #MESA" would mean that the ore may spawn in the "byg:guiana_shield" OR all biomes in the "MESA" category.
#3. "byg#ICY$MOUNTAIN" would mean that the ore may only spawn in biomes from byg in the "ICY" category and "MOUNTAIN" dictionary type.
#4. "!byg#DESERT" would mean that the ore may only spawn in biomes that are NOT from byg and NOT in the "DESERT" category.
#5. "ALL", spawn everywhere. 
#6. "" Don't spawn anywhere.
[ores]
	#What biome(s) does Ametrine spawn in? Default: "byg:shattered_viscal_isles".
	ametrineSpawns = "byg:shattered_viscal_isles"
	#What biome(s) does Budding Ametrine spawn in? Default: "byg:shattered_viscal_isles".
	buddingAmetrineSpawns = "byg:shattered_viscal_isles"
	#What biome(s) does Emeraldite spawn in? Default: "byg:wailing_garth".
	emeralditeSpawns = "byg:wailing_garth"
	#What biome(s) does Pendorite spawn in? Default: "byg:embur_bog".
	pendoriteSpawns = "byg:embur_bog"
	#What biome(s) does Therium spawn in? Default: "byg#THE_END".
	theriumSpawns = "byg#THEEND"

#See the explanation for ores for configuring stones.
[stones]
	#What biome(s) does Rocky Stone spawn in? Default: "!#THEEND#NETHER".
	rockyStoneSpawns = "!#THEEND#NETHER"
	#What biome(s) does Scoria Stone spawn in? Default: "!#THEEND#NETHER".
	scoriaStoneSpawns = "!#THEEND#NETHER"
	#What biome(s) does Soap Stone spawn in? Default: "!#THEEND#NETHER".
	soapStoneSpawns = "!#THEEND#NETHER"

